peer:
    id: peer0.ec.example.com
    networkId: dev
    listenAddress: 0.0.0.0:7051
    chaincodeListenAddress: 0.0.0.0:7052
    chaincodeAddress: peer0.ec.example.com:7052
    address: peer0.ec.example.com:7051
    addressAutoDetect: false
    
    # BCCSP (Blockchain Crypto Service Provider) Configuration
    BCCSP:
        Default: SW
        SW:
            Hash: SHA2
            Security: 256
        
    # TLS Configuration
    tls:
        enabled: true
        cert:
            file: config/crypto-config/peerOrganizations/ec.example.com/peers/peer0.ec.example.com/tls/server.crt
        key:
            file: config/crypto-config/peerOrganizations/ec.example.com/peers/peer0.ec.example.com/tls/server.key
        rootcert:
            file: config/crypto-config/peerOrganizations/ec.example.com/peers/peer0.ec.example.com/tls/ca.crt
            
    # MSP Configuration
    mspConfigPath: config/crypto-config/peerOrganizations/ec.example.com/users/Admin@ec.example.com/msp
    localMspId: ElectionCommissionMSP
    
    # File System Path
    fileSystemPath: /var/hyperledger/production
